package com.carddemo.domain;
import jakarta.persistence.*;
/** Customer record RECLN 500. */
@Entity @Table(name="customer")
public class Customer {
 @Id @Column(name="cust_id") private Long customerId;
 @Column(name="cust_first_name",length=25,nullable=false) private String firstName; @Column(name="cust_middle_name",length=25,nullable=false) private String middleName; @Column(name="cust_last_name",length=25,nullable=false) private String lastName;
 @Column(name="cust_addr_line_1",length=50,nullable=false) private String addressLine1; @Column(name="cust_addr_line_2",length=50,nullable=false) private String addressLine2; @Column(name="cust_addr_line_3",length=50,nullable=false) private String addressLine3; @Column(name="cust_addr_state_cd",length=2,nullable=false) private String stateCode; @Column(name="cust_addr_country_cd",length=3,nullable=false) private String countryCode; @Column(name="cust_addr_zip",length=10,nullable=false) private String zip; @Column(name="cust_phone_num_1",length=15,nullable=false) private String phone1; @Column(name="cust_phone_num_2",length=15,nullable=false) private String phone2;
 @Column(name="cust_ssn",nullable=false) private Long ssn; @Column(name="cust_govt_issued_id",length=20,nullable=false) private String govtIssuedId; @Column(name="cust_dob_yyyy_mm_dd",length=10,nullable=false) private String dateOfBirth; @Column(name="cust_eft_account_id",length=10,nullable=false) private String eftAccountId; @Column(name="cust_pri_card_holder_ind",length=1,nullable=false) private String primaryCardHolder; @Column(name="cust_fico_credit_score",nullable=false) private Integer ficoCreditScore;
 public Long getCustomerId(){return customerId;} public void setCustomerId(Long v){customerId=v;} public String getFirstName(){return firstName;} public void setFirstName(String v){firstName=v;} public String getMiddleName(){return middleName;} public void setMiddleName(String v){middleName=v;} public String getLastName(){return lastName;} public void setLastName(String v){lastName=v;} public String getAddressLine1(){return addressLine1;} public void setAddressLine1(String v){addressLine1=v;} public String getAddressLine2(){return addressLine2;} public void setAddressLine2(String v){addressLine2=v;} public String getAddressLine3(){return addressLine3;} public void setAddressLine3(String v){addressLine3=v;} public String getStateCode(){return stateCode;} public void setStateCode(String v){stateCode=v;} public String getCountryCode(){return countryCode;} public void setCountryCode(String v){countryCode=v;} public String getZip(){return zip;} public void setZip(String v){zip=v;} public String getPhone1(){return phone1;} public void setPhone1(String v){phone1=v;} public String getPhone2(){return phone2;} public void setPhone2(String v){phone2=v;} public Long getSsn(){return ssn;} public void setSsn(Long v){ssn=v;} public String getGovtIssuedId(){return govtIssuedId;} public void setGovtIssuedId(String v){govtIssuedId=v;} public String getDateOfBirth(){return dateOfBirth;} public void setDateOfBirth(String v){dateOfBirth=v;} public String getEftAccountId(){return eftAccountId;} public void setEftAccountId(String v){eftAccountId=v;} public String getPrimaryCardHolder(){return primaryCardHolder;} public void setPrimaryCardHolder(String v){primaryCardHolder=v;} public Integer getFicoCreditScore(){return ficoCreditScore;} public void setFicoCreditScore(Integer v){ficoCreditScore=v;}
}
