CREATE TABLE customer (
 cust_id BIGINT PRIMARY KEY, cust_first_name VARCHAR(25) NOT NULL, cust_middle_name VARCHAR(25) NOT NULL, cust_last_name VARCHAR(25) NOT NULL,
 cust_addr_line_1 VARCHAR(50) NOT NULL, cust_addr_line_2 VARCHAR(50) NOT NULL, cust_addr_line_3 VARCHAR(50) NOT NULL, cust_addr_state_cd VARCHAR(2) NOT NULL,
 cust_addr_country_cd VARCHAR(3) NOT NULL, cust_addr_zip VARCHAR(10) NOT NULL, cust_phone_num_1 VARCHAR(15) NOT NULL, cust_phone_num_2 VARCHAR(15) NOT NULL,
 cust_ssn BIGINT NOT NULL, cust_govt_issued_id VARCHAR(20) NOT NULL, cust_dob_yyyy_mm_dd VARCHAR(10) NOT NULL, cust_eft_account_id VARCHAR(10) NOT NULL,
 cust_pri_card_holder_ind VARCHAR(1) NOT NULL, cust_fico_credit_score INTEGER NOT NULL
);
CREATE TABLE account (
 acct_id BIGINT PRIMARY KEY, acct_active_status VARCHAR(1) NOT NULL, acct_curr_bal NUMERIC(12,2) NOT NULL, acct_credit_limit NUMERIC(12,2) NOT NULL,
 acct_cash_credit_limit NUMERIC(12,2) NOT NULL, acct_open_date VARCHAR(10) NOT NULL, acct_expiration_date VARCHAR(10) NOT NULL, acct_reissue_date VARCHAR(10) NOT NULL,
 acct_curr_cyc_credit NUMERIC(12,2) NOT NULL, acct_curr_cyc_debit NUMERIC(12,2) NOT NULL, acct_addr_zip VARCHAR(10) NOT NULL, acct_group_id VARCHAR(10) NOT NULL
);
CREATE TABLE card (card_num CHAR(16) PRIMARY KEY, card_acct_id BIGINT NOT NULL, card_cvv_cd INTEGER NOT NULL, card_embossed_name VARCHAR(50) NOT NULL, card_expiration_date VARCHAR(10) NOT NULL, card_active_status VARCHAR(1) NOT NULL);
CREATE TABLE card_xref (xref_card_num CHAR(16) PRIMARY KEY, xref_cust_id BIGINT NOT NULL, xref_acct_id BIGINT NOT NULL);
CREATE INDEX idx_card_xref_acct ON card_xref(xref_acct_id);
CREATE TABLE transaction_record (tran_id CHAR(16) PRIMARY KEY, tran_type_cd CHAR(2) NOT NULL, tran_cat_cd INTEGER NOT NULL, tran_source VARCHAR(10) NOT NULL, tran_desc VARCHAR(100) NOT NULL, tran_amt NUMERIC(11,2) NOT NULL, tran_merchant_id BIGINT NOT NULL, tran_merchant_name VARCHAR(50) NOT NULL, tran_merchant_city VARCHAR(50) NOT NULL, tran_merchant_zip VARCHAR(10) NOT NULL, tran_card_num CHAR(16) NOT NULL, tran_orig_ts VARCHAR(26) NOT NULL, tran_proc_ts VARCHAR(26) NOT NULL);
-- Mirrors AWS.M2.CARDDEMO.TRANSACT.VSAM.AIX KEYS(26 304) from app/jcl/TRANFILE.jcl.
CREATE INDEX idx_transaction_proc_ts ON transaction_record(tran_proc_ts);
CREATE TABLE daily_transaction (dailytran_id CHAR(16) PRIMARY KEY, dailytran_type_cd CHAR(2) NOT NULL, dailytran_cat_cd INTEGER NOT NULL, dailytran_source VARCHAR(10) NOT NULL, dailytran_desc VARCHAR(100) NOT NULL, dailytran_amt NUMERIC(11,2) NOT NULL, dailytran_merchant_id BIGINT NOT NULL, dailytran_merchant_name VARCHAR(50) NOT NULL, dailytran_merchant_city VARCHAR(50) NOT NULL, dailytran_merchant_zip VARCHAR(10) NOT NULL, dailytran_card_num CHAR(16) NOT NULL, dailytran_orig_ts VARCHAR(26) NOT NULL, dailytran_proc_ts VARCHAR(26) NOT NULL);
CREATE TABLE tran_cat_balance (trancat_acct_id BIGINT NOT NULL, trancat_type_cd VARCHAR(2) NOT NULL, trancat_cd INTEGER NOT NULL, tran_cat_bal NUMERIC(11,2) NOT NULL, PRIMARY KEY (trancat_acct_id,trancat_type_cd,trancat_cd));
CREATE TABLE disclosure_group (dis_acct_group_id VARCHAR(10) NOT NULL, dis_tran_type_cd VARCHAR(2) NOT NULL, dis_tran_cat_cd INTEGER NOT NULL, dis_int_rate NUMERIC(6,2) NOT NULL, PRIMARY KEY (dis_acct_group_id,dis_tran_type_cd,dis_tran_cat_cd));
CREATE TABLE transaction_type (tran_type VARCHAR(2) PRIMARY KEY, tran_type_desc VARCHAR(50) NOT NULL);
CREATE TABLE transaction_category (tran_type_cd VARCHAR(2) NOT NULL, tran_cat_cd INTEGER NOT NULL, tran_cat_type_desc VARCHAR(50) NOT NULL, PRIMARY KEY (tran_type_cd,tran_cat_cd));
CREATE TABLE daily_transaction_reject (reject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, raw_record CHAR(350) NOT NULL, reject_reason_code INTEGER NOT NULL, reason_description VARCHAR(76) NOT NULL, rejected_at TIMESTAMP NOT NULL);
